- core/include/array/include/algebra/definitions/array.hpp
Without `inline`, the cuda source files are not compiled due to multiple definitions. I think it happens source files include array header several times.
> add inline to array functions

- CMakeLists.txt
- core/include/eigen/CMakeLists.txt
I removed the include directory since it didn't work for me (Eigen3_include_dir keeps referring ridiculous directory which doesn't have eigen 3.3.7 source). I don't know if it happens to other people.
Anyway I replace it with target_llink_libraries, which should be better.
@asalzburger @paulgessinger
> remove include dir for eigen and replace it with target link libraries

- core/include/eigen/include/algebra/definitions/eigen.hpp
Rotate function of eigen plugin is missing so I added it 
The input type (`Eigen::Transform<scalar, 3, Eigen::Affine>`) of eigen rotate function follows the type of `_data`
as the input type (`matrix44`) of array rotate function does. So we still keep the same usage for those plugins
@niermann999 @asalzburger would you review quickly as it is tiny PR?
> add rotate function to eigen

- CMakeLists.txt
As this is generally a submodule, the unittests should only be build, when specifically requested
> fix: set build unittest to off

- extern/CMakeLists.txt
Currently in traccc, the compilation fails due to double population of vecmem (one from algebra plugin, and one from direct population) Let's avoid that
> avoid duplicate population of vecmem

- extern/eigen3/CMakeLists.txt
cuda eigen unit test file of acts-project/detray#133 does NOT work with eigen 3.3.9. (Compilation was OK but zero output from `point_to_global`)
eigen 3.4.0 solves the issue.
> Update to Eigen 3.4.0

- frontend/array_cmath/include/algebra/array_cmath.hpp
- frontend/eigen_cmath/include/algebra/eigen_cmath.hpp
- frontend/smatrix_cmath/include/algebra/smatrix_cmath.hpp
- frontend/vc_cmath/include/algebra/vc_cmath.hpp
- frontend/vecmem_cmath/include/algebra/vecmem_cmath.hpp
- math/cmath/include/algebra/math/impl/cmath_getter.hpp
- math/cmath/include/algebra/math/impl/cmath_operator.hpp
- math/cmath/include/algebra/math/impl/cmath_transform3.hpp
- math/cmath/include/algebra/math/impl/cmath_vector.hpp
Removed the `auto` size type specifications from the `algebra::cmath_math` code. As it was discovered by @beomki-yeo in https://github.com/acts-project/detray/pull/134, CUDA does not understand the formalism that the code used so far. :frowning:
All of the "free-standing" functions were updated to receive yet another template parameter, with the "size type". For this to work I had to make all of those functions make explicit use of the size type parameter. For instance turning:
```c++
template <template <typename, auto> class array_t, typename scalar_t>
ALGEBRA_HOST_DEVICE inline scalar_t dot(const array_t<scalar_t, 2> &a,
const array_t<scalar_t, 2> &b) {
return a[0] * b[0] + a[1] * b[1];
}
```
into:
```c++
template <typename size_type, template <typename, size_type> class array_t, …
```
> Remove "auto" from algebra::cmath_math, main branch (2021.11.02.)

- CMakeLists.txt
- extern/vc/CMakeLists.txt
- extern/vecmem/CMakeLists.txt
Updated the VecMem and Vc builds.
- [Vc](https://github.com/VcDevel/Vc) is now downloaded as a TGZ file, instead of downloading the entire Git repository.
* This was bothering me quite a bit in recent weeks. That it currently takes a long time to download Vc for the build.
- [VecMem](https://github.com/acts-project/vecmem) is updated to version [v0.7.0](https://github.com/acts-project/vecmem/releases/tag/v0.7.0), and the "language code" from it is activated for this project.
* In case we ever want to add any CUDA/HIP/SYCL tests to this project.
* This is done in the same way as in https://github.com/acts-project/traccc/pull/106.
I also enabled the setup of VecMem by default for the project. Every other "traccc project" depends on VecMem by now. We may want to make that mandatory here as …
> External Updates, main branch (2021.11.08.)

- .github/workflows/builds.yml
- tests/accelerator/CMakeLists.txt
- tests/accelerator/cuda/common/test_cuda_basics.cuh
As I mentioned in #39, we don't yet perform the CUDA tests in the CI.
I re-organised the CI configuration in the style that we use in [vecmem](https://github.com/acts-project/vecmem) these days.
- I separately set up "native" and "containerized" tests;
- The native tests turn on every feature that they can, and only test such a fully loaded configuration;
- For the containerized tests, the "host tests" turn on features one-by-one, to test that those can function individually. And not just when everything else is also turned on.
- The "cuda test", similar to the "native tests", only runs on one configurations, with everything possible turned on at once.
Note that I decided not to use every combination of build mode and scalar type in the tests individually. Since I intend to get rid of the …
> CI Update, main branch (2021.11.18.)

- .github/workflows/builds.yml
- CMakeLists.txt
- cmake/algebra-plugins-compiler-options.cmake
- cmake/algebra-plugins-functions.cmake
- tests/CMakeLists.txt
- tests/accelerator/cuda/CMakeLists.txt
- tests/accelerator/cuda/common/execute_cuda_test.cuh
- tests/accelerator/cuda/common/test_cuda_basics.cuh
- tests/accelerator/cuda/common/test_cuda_basics_functors.hpp
- tests/common/test_host_basics.hpp
These changes are set up on top of #41. So I'll keep it in a draft stage until that PR is sorted out.
I hope you all saw this coming. :stuck_out_tongue: I just really wanted to see if I could build this project on Windows as well. :smile: Turns out, we can. It only required a couple of changes. All of them in the test code, and not in the main headers / libraries of the project.
Note that unfortunately with CUDA enabled, I see a large number of warnings. Most of them coming from Eigen. But there are also some coming when `nvcc` is making use of [vecmem/memory/details/memory_resource_base.hpp](https://github.com/acts-project/vecmem/blob/main/core/include/vecmem/memory/details/memory_resource_base.hpp). It seems that we'll need to find the equivalent of
```c++
#ifdef _MSC_VER
#pragma …
```
> Windows Compatibility, main branch (2021.11.18.)

- .github/ci_setup.sh
- .github/workflows/builds.yml
- math/CMakeLists.txt
- math/cmath/CMakeLists.txt
- math/cmath/include/algebra/math/impl/cmath_getter.hpp
- math/cmath/include/algebra/math/impl/cmath_vector.hpp
- math/common/CMakeLists.txt
- math/common/include/algebra/math/common.hpp
- math/eigen/CMakeLists.txt
- math/eigen/include/algebra/math/impl/eigen_getter.hpp
- math/vc/CMakeLists.txt
- math/vc/include/algebra/math/impl/vc_getter.hpp
- math/vc/include/algebra/math/impl/vc_vector.hpp
- storage/smatrix/include/algebra/storage/smatrix.hpp
- tests/accelerator/CMakeLists.txt
- tests/accelerator/common/test_basics_base.hpp
- tests/accelerator/common/test_basics_functors.hpp
- tests/accelerator/cuda/CMakeLists.txt
- tests/accelerator/sycl/CMakeLists.txt
- tests/accelerator/sycl/array_cmath.sycl
- tests/accelerator/sycl/common/execute_sycl_test.hpp
- tests/accelerator/sycl/common/test_sycl_basics.hpp
- tests/accelerator/sycl/vecmem_cmath.sycl
This -- in the end -- fairly substantial update was triggered by the errors seen in @konradkusiak97's developments in [traccc](https://github.com/acts-project/traccc). Which lead to the opening of the following ticket: https://github.com/intel/llvm/issues/5326
What we came across is that it would be impossible to use [std::atan2](https://en.cppreference.com/w/cpp/numeric/math/atan2) (and some other math functions) in SYCL device code on non-Intel backends. For the CUDA and HIP backends we must use `cl::sycl::atan2` instead.
For this I ended up introducing `algebra/math/common.hpp`, which would declare all of the "standard" math functions that we use in a couple of places in the code. This part was relatively simple.
But then I decided that we really also need to have explicit SYCL tests …
> Improved SYCL Math Support, main branch (2022.01.18.)

- math/eigen/include/algebra/math/impl/eigen_transform3.hpp
This is a fix to a bug that @krasznaa alerted me of yesterday, where under some very strict set of circumstances, the Eigen tests would fail to run, giving an invalid memory access error. For this to happen, the code must be compiled in `Debug` build mode.
Anyway, the error results from the fact that the matrices in our Eigen `transform3` class are all defaulted to the `Identity()` transformation. While this should be fine, it apparently does not work well with CUDA. Thus, the solution is to remove these defaults and explicitly set the matrices to identity matrices using `setIdentity()`.
Without going deep into the Eigen3 code, I can only speculate _why_ this bug happens. One semi-likely explanation might be that the identity matrices are stored in the `.data` or `.bss` sections of the …
> Fix identity error in CUDA debug builds with Eigen

- math/cmath/include/algebra/math/impl/cmath_getter.hpp
- tests/common/test_host_basics.hpp
Fixed a warning coming from MSVC in `algebra::cmath::vector_getter`. It showed up while trying to build [detray](https://github.com/acts-project/detray) with MSVC. (Oh yeah, that is coming! MSVC complains about a lot of funky business in that project, for pretty good reasons...)
Added code for triggering the issue, so that this project would check that function explicitly as well. Even if the return value of that function is not checked. Because that return value is not independent of the plugin type being used...
Keeping it as a draft for now, as I'll only finalise it once detray builds successfully on Windows. :wink:
> More MSVC Fixes, main branch (2022.02.04.)

- frontend/array_cmath/include/algebra/array_cmath.hpp
- frontend/eigen_cmath/include/algebra/eigen_cmath.hpp
- frontend/smatrix_cmath/include/algebra/smatrix_cmath.hpp
- frontend/vc_cmath/include/algebra/vc_cmath.hpp
- frontend/vc_vc/include/algebra/vc_vc.hpp
- frontend/vecmem_cmath/include/algebra/vecmem_cmath.hpp
- math/cmath/include/algebra/math/algorithms/matrix/determinant/hard_coded.hpp
- math/cmath/include/algebra/math/algorithms/matrix/inverse/hard_coded.hpp
- math/cmath/include/algebra/math/impl/cmath_matrix.hpp
- math/cmath/include/algebra/math/impl/cmath_transform3.hpp
- math/eigen/include/algebra/math/impl/eigen_getter.hpp
- math/eigen/include/algebra/math/impl/eigen_matrix.hpp
- math/eigen/include/algebra/math/impl/eigen_transform3.hpp
- math/smatrix/include/algebra/math/impl/smatrix_getter.hpp
- math/smatrix/include/algebra/math/impl/smatrix_matrix.hpp
- math/smatrix/include/algebra/math/impl/smatrix_transform3.hpp
- math/vc/include/algebra/math/impl/vc_transform3.hpp
- storage/eigen/include/algebra/storage/impl/eigen_array.hpp
- tests/common/test_host_basics.hpp
- tests/vc/vc_cmath.cpp
This PR makes `cmath::transform3` have `matrix::actor` as a template parameter.
Hard coded inversion and determinant of 4x4 matrix are moved to cmath::matrix algorithms as well
> Refactor Transform3 with Matrix Actor

- math/cmath/include/algebra/math/impl/cmath_matrix.hpp
- math/eigen/include/algebra/math/impl/eigen_matrix.hpp
- math/smatrix/include/algebra/math/impl/smatrix_matrix.hpp
- tests/common/test_device_basics.hpp
- tests/common/test_host_basics.hpp
This is possibly the last update for the moment ( I hope ... )
This PR adds `set_block` function to matrix backend.
Eigen backend doesn't need `set_block` as `block` supports lvalue.
Meanwhile, `block` operator of cmath and smtrix backends don't support lvalue so I needed to setup a new function
Yeah so it is an awful implementation and might degrade the performance. We need to think about how to make all backends support lvalue block operation. Or, at least find a better alternative
Following snippet is what I want to achieve in the end
```c++
matrix<4,4> m;
auto b22 = matrix_actor().template block<2,2>(m,1,1); // get 2x2 block matrix which can be used as lvalue
element_getter()(b22,0,0) = 1; //  m(1,1) is also changed
```
> Add set block function in matrix

- frontend/array_cmath/include/algebra/array_cmath.hpp
- frontend/eigen_cmath/include/algebra/eigen_cmath.hpp
- frontend/smatrix_cmath/include/algebra/smatrix_cmath.hpp
- frontend/vc_cmath/include/algebra/vc_cmath.hpp
- frontend/vc_vc/include/algebra/vc_vc.hpp
- frontend/vecmem_cmath/include/algebra/vecmem_cmath.hpp
- tests/accelerator/cuda/array_cmath.cu
- tests/accelerator/cuda/eigen_cmath.cu
- tests/accelerator/cuda/vecmem_cmath.cu
- tests/accelerator/sycl/array_cmath.sycl
- tests/accelerator/sycl/vecmem_cmath.sycl
- tests/array/array_cmath.cpp
- tests/eigen/eigen_cmath.cpp
- tests/smatrix/smatrix_cmath.cpp
- tests/vc/vc_cmath.cpp
- tests/vc/vc_vc.cpp
- tests/vecmem/vecmem_cmath.cpp
Matrix actors in frontends don't have to take `size_type` as a template parameter obviously...
> Remove size type parameter in frontend matrix actor

- frontend/array_cmath/include/algebra/array_cmath.hpp
- frontend/eigen_cmath/include/algebra/eigen_cmath.hpp
- frontend/smatrix_cmath/include/algebra/smatrix_cmath.hpp
- frontend/vc_cmath/include/algebra/vc_cmath.hpp
- frontend/vc_vc/include/algebra/vc_vc.hpp
- storage/array/include/algebra/storage/array.hpp
- storage/eigen/include/algebra/storage/eigen.hpp
- storage/smatrix/include/algebra/storage/smatrix.hpp
- storage/vc/include/algebra/storage/vc.hpp
With the change in the PR we can define `size_type` for matrix in external projects:
```
using size_type = __plugin::size_type
```
> Add `size_type` to plugin namespace

- math/cmath/include/algebra/math/impl/cmath_transform3.hpp
- math/eigen/include/algebra/math/impl/eigen_matrix.hpp
- math/eigen/include/algebra/math/impl/eigen_transform3.hpp
- math/smatrix/include/algebra/math/impl/smatrix_transform3.hpp
- math/smatrix/include/algebra/math/impl/smatrix_vector.hpp
- math/vc/include/algebra/math/impl/vc_transform3.hpp
- storage/eigen/include/algebra/storage/eigen.hpp
- tests/common/test_device_basics.hpp
- tests/common/test_host_basics.hpp
There are three updates in this PR:
- Add `matrix_inverse` method in `transform3` classes
- Allow dot product between `SVector` and `SMatrix<N,1>`
- Define Eigen matrix as `Row major` when the number of rows is one (Otherwise, compiler spits error message with invalid template parameter)
> Stability improvement

- math/cmath/include/algebra/math/impl/cmath_transform3.hpp
- math/eigen/include/algebra/math/impl/eigen_transform3.hpp
- math/smatrix/include/algebra/math/impl/smatrix_transform3.hpp
- math/vc/include/algebra/math/impl/vc_transform3.hpp
This PR adds a constructor of `transform3` which takes `t`,`x`,`y`,`z` and `get_inverse` as inputs. The last argument is to decide whether to calculate inverse or not. (I have a use case for creating tf3 object without inverse)
The old constructor also utilizes the new constructor to avoid code repetition.
> Add a constructor for transform3

- CMakeLists.txt
Addresses #82.
I used `ALGEBRA_PLUGINS_USE_SYSTEM_LIBS` everywhere (i.e. for Vc, Fastor, and Eigen) so that now there is no surprise about why, say, Fastor is searching for a system library even though `-DALGEBRA_PLUGINS_USE_SYSTEM_LIBS=TRUE` was passed.
> Use `ALGEBRA_PLUGINS_USE_SYSTEM_LIBS` across the board for configuration

- math/cmath/include/algebra/math/impl/cmath_getter.hpp
Since ```SIZE``` encodes the number of elements to get, it should be ```<=``` the number of ```ROWS```
> fix: assert in cmath vector getter

- extern/vecmem/CMakeLists.txt
Switched to using [VecMem 0.22.0](https://github.com/acts-project/vecmem/releases/tag/v0.22.0) by default.
While testing #90 I was using a recent nightly of [intel/llvm](https://github.com/intel/llvm), which the old version of VecMem is just not compatible with anymore. While having the old VecMem version in the CI was a fairly good test for API stability in that project, making it easier to build this project with the newest compilers is more important. :wink:
> VecMem Update, main branch (2023.02.03.)

- .gitattributes
Taught GitHub how to highlight code in `.sycl` files. Exactly how it is done in [vecmem](https://github.com/acts-project/vecmem) and [traccc](https://github.com/acts-project/traccc) as well.
> GitHub SYCL Highlighting, main branch (2023.02.03.)

- math/cmath/include/algebra/math/algorithms/utils/algorithm_finder.hpp
- math/smatrix/include/algebra/math/impl/smatrix_matrix.hpp
- tests/common/test_host_basics.hpp
Casts to `void` (to suppress unused variable warnings) look like black boxes to unsuspecting readers of the code. `[[maybe_unused]]` is a much better way to convey intent.
Moreover, since we are using C++17, there is no reason not to use `[[maybe_unused]]` as it available in any C++17-standard compliant compiler.
> Replaced casts to `void` with the `[[maybe_unused]]` attribute.

- math/cmath/include/algebra/math/impl/cmath_matrix.hpp
- math/eigen/include/algebra/math/impl/eigen_matrix.hpp
- math/smatrix/include/algebra/math/impl/smatrix_matrix.hpp
I marked the all the `actor` member functions as `const` to improve `const`-correctness. They can all be marked as `const` because none of them change the internal state of the `actor` struct.
> `actor` member functions marked as `const`

- cmake/algebra-plugins-config.cmake.in
Moved the use of "magic variables" before the first use of find_dependency to fix #36. (This of course also very much relates to https://github.com/acts-project/traccc/pull/364.)
The way that the variables provided by [configure_package_config_file(...)](https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html#command:configure_package_config_file) work is that a "`PACKAGE_PREFIX_DIR`" variable is created behind the scenes, and all other variables are declared relative to this "hidden" variable.
The problem is that if a package "found" by [find_dependency(...)](https://cmake.org/cmake/help/latest/module/CMakeFindDependencyMacro.html) uses the same CMake mechanism in its own exported CMake configuration (like [Vc](https://github.com/VcDevel/Vc) does for instance), then …
> CMake Export Fix, main branch (2023.03.24.)

- extern/vecmem/CMakeLists.txt
Updated the project to use [vecmem-0.24.0](https://github.com/acts-project/vecmem/releases/tag/v0.24.0).
A bit surprisingly none of the tests in this project use vector buffers, so the code didn't actually need to be updated...
> VecMem Update, main branch (2023.03.29.)

- .github/workflows/builds.yml
- CMakeLists.txt
Removed the reference to the non-existent `benchmarks/` directory. This was introduced in #69, which I just really don't see the point in now that I look back. :frowning: (One would only add Google Benchmark in the PR in which it is first needed. And touching all those files without a need is just pretty bad... :frowning:)
At the same time enabled the "build of benchmarks" in the CI. In case we ever add some to the project...
> Benchmarks Fix, main branch (2023.03.29.)

- CMakeLists.txt
- cmake/algebra-plugins-functions.cmake
- common/CMakeLists.txt
- frontend/array_cmath/CMakeLists.txt
- frontend/eigen_cmath/CMakeLists.txt
- frontend/eigen_eigen/CMakeLists.txt
- frontend/fastor_fastor/CMakeLists.txt
- frontend/smatrix_cmath/CMakeLists.txt
- frontend/smatrix_smatrix/CMakeLists.txt
- frontend/vc_cmath/CMakeLists.txt
- frontend/vc_vc/CMakeLists.txt
- frontend/vecmem_cmath/CMakeLists.txt
- math/cmath/CMakeLists.txt
- math/common/CMakeLists.txt
- math/eigen/CMakeLists.txt
- math/fastor/CMakeLists.txt
- math/smatrix/CMakeLists.txt
- math/vc/CMakeLists.txt
- storage/array/CMakeLists.txt
- storage/eigen/CMakeLists.txt
- storage/fastor/CMakeLists.txt
- storage/smatrix/CMakeLists.txt
- storage/vc/CMakeLists.txt
- storage/vecmem/CMakeLists.txt
This is a sibling of https://github.com/acts-project/vecmem/pull/222.
I added a function called `algebra_test_public_headers(...)` that can be used to make sure that:
- public header files include everything that they need to be usable;
- the CMake library targets are set up correctly to make the public headers usable after only linking against the library target that the public header is sitting in.
All this was necessitated because I noticed in [traccc](https://github.com/acts-project/traccc) that some [detray](https://github.com/acts-project/detray) targets are not set up correctly. :frowning: But introducing rigorous tests revealed some problems already in [vecmem](https://github.com/acts-project/vecmem), and now in this project as well. (The `algebra::eigen_math`, …
> Public Header Tests, main branch (2023.03.29.)

- README.md
I removed it because it looks like the current `CMakeLists.txt` does not use this option. It appears to have been removed in f4701ab13bd578eb5a486b65d1c461497573ece0 as a part of #44.
> Removed `ALGEBRA_PLUGINS_CUSTOM_SCALARTYPE` option from the README.

- extern/eigen3/CMakeLists.txt
Let me revert the eigen version as it turned out that 3.4.1 tag actually doesn't exist
> Rollback to eigen 3.4.0

- tests/accelerator/sycl/common/test_sycl_basics.hpp
Some of the Intel (i)GPUs don't have native FP64 support. This update makes sure that tests would not fail on them because of this.
Without these checks, I would get the following on my laptop:
```
[ RUN      ] algebra_plugins/test_sycl_basics/sycl_array_cmath<double>.transform3
unknown file: error: C++ exception with description "Required aspect fp64 is not supported on the device" thrown in the test body.        
[  FAILED  ] algebra_plugins/test_sycl_basics/sycl_array_cmath<double>.transform3, ...
```
> SYCL FP64 Test Skips, main branch (2023.10.06.)

- .github/ci_setup.sh
- .github/workflows/builds.yml
- CMakePresets.json
Add a `CMakePresets.json` file to the repository. And also updated the CI to make use of it, simplifying the latter a little.
Presets are described here:
https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html
I've been thinking for a long time about adopting them in our projects to simplify builds a little bit. Since especially in this project (as @niermann999 has also rightfully complained in the past) we need to use an unreasonable number of CMake CACHE variables to specify exactly what type of build we want. With this setup the idea is that we could do:
```
cmake --preset default ../algebra-plugins/
```
Or:
```
cmake --preset cuda ../algebra-plugins/
```
Etc.
Note that it's very possible to use CACHE variable declarations together with the presets. Like:
```
cmake --preset …
```
> CMake Presets, main branch (2023.10.06.)

- math/eigen/include/algebra/math/impl/eigen_getter.hpp
- math/eigen/include/algebra/math/impl/eigen_matrix.hpp
- math/eigen/include/algebra/math/impl/eigen_transform3.hpp
- math/eigen/include/algebra/math/impl/eigen_vector.hpp
- storage/eigen/include/algebra/storage/impl/eigen_array.hpp
Turned off specific CUDA warnings for the Eigen headers.
This is only needed with MSVC, since "system include directories" as a concept doesn't quite work with that compiler. 😦 (On Linux we are shielded from these warnings by: https://github.com/acts-project/algebra-plugins/blob/main/extern/eigen3/CMakeLists.txt#L39-L44) So we need to explicitly turn off the checking for some warnings in the code like this.
@niermann999, you mentioned in https://github.com/acts-project/algebra-plugins/pull/95#issuecomment-1752741760 that you observe warnings yourself as well. Could you elaborate? Since I only know at this point why there would be warnings on Windows. But on Linux there should not have been any to begin with. 🤔
P.S. Note that the `master` branch of Eigen doesn't produce any warnings/errors …
> Silence Eigen Warnings From CUDA on Windows, main branch (2023.10.09.)

- .github/workflows/builds.yml
- CMakePresets.json
- extern/fastor/CMakeLists.txt
Added a separate default configuration for the `aarch64` platform. Since as it turns out, Fastor does not work on non-x86 platforms. (Like my M1 Mac.) So provided a configuration preset without Fastor for `aarch64`.
Note that interestingly the GitHub runners seem to **not** use ARM Mac-s. 😕 Since those build succeeded so far, and I also don't see
```
-- Building Vc as part of the Algebra Plugins project
-- Detected Compiler: Clang 15.0.0
CMake Warning at /Users/krasznaa/ATLAS/projects/algebra/build/_deps/vc-src/CMakeLists.txt:34 (message):
No optimized implementation of the Vc types available for arm64
```
in their configuration logs. 🤔
Also note that I'm very much getting the feeling that the CPU architecture may have something to do with your Mac troubles in #95 @niermann999, but I'll …
> Add CMake Preset for ARM64, main branch (2023.10.14.)

- common/include/algebra/qualifiers.hpp
As proposed by @krasznaa in https://github.com/acts-project/vecmem/pull/261, extend the __host__ and __device__ macros for HIP.
> Make __host__ and __device__ function checks work with HIP

- .gitignore
Made git ignore the directory created by VSCode during its build (`out/`).
For some reason I forgot to add this back in #109 and #111. :confused:
> (Better) VSCode Build Support, main branch (2024.04.11.)

- math/cmath/include/algebra/math/algorithms/matrix/decomposition/partial_pivot_lud.hpp
- math/common/include/algebra/math/common.hpp
As one might guess, #113 and #114 were just collateral updates for this PR. :stuck_out_tongue:
With [oneAPI 2024.1.0](https://www.intel.com/content/www/us/en/developer/articles/release-notes/intel-oneapi-dpc-c-compiler-release-notes.html) Intel switched to enforcing [SYCL 2020](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html) rules more strictly than it did earlier. And as it turns out, using [std::abs](https://en.cppreference.com/w/cpp/numeric/math/fabs) with floating point numbers is no longer okay in SYCL device code. :thinking: Leading to the following, very non-descriptive linker error:
```
[build] ptxas fatal   : Unresolved extern function 'fabs'
[build] llvm-foreach: 
[build] ptxas fatal   : Unresolved extern function 'fabsf'
[build] llvm-foreach: 
[build] …
```
> oneAPI 2024.1.0 Support, main branch (2024.04.11.)

- cmake/algebra-plugins-compiler-options-sycl.cmake
- extern/vecmem/CMakeLists.txt
Updated the project to [VecMem 1.4.0](https://github.com/acts-project/vecmem/releases/tag/v1.4.0).
At the same time simplified the SYCL build flag configuration of the project a bit, which the new VecMem version allows to do. :wink:
> VecMem (and CMake) Update, main branch (2024.04.11.)

- math/cmath/include/algebra/math/impl/cmath_matrix.hpp
- math/cmath/include/algebra/math/impl/cmath_operators.hpp
- tests/common/test_host_basics.hpp
Free lunch time
Just to help understanding what's going on with new matrix multiplication.
It should be noted that the cmath matrix is made of multiple arrays where each of them represents each **column** of matrix. 
Imagine that we do multiply 4x4 matrix **A** and **B** to obtain the matrix **C**. If we do the matrix multiplication as we usually do like the following figure, we will have to pick up the row of **A** which cannot be vectorized:
So I came up with an idea to do the matrix multiplication column-wisely by multiplying a column of **A** to the element of **B**:
```c++
for (size_type k = 0; k < M; ++k) {
C[j][k] += A[i][k] * B[j][i];
}
```
The following figure shows how the column of **C** is calculated in the new matrix multiplication
> Vectorize the cmath matrix operations

- .github/workflows/builds.yml
XCode refuses to compile algebra-plugins with the Fastor plugin turned on, and this is causing the CI to fail. This commit disables Fastor in the macOS CI job to ensure that it runs through.
> Disable Fastor in macOS CI job

- extern/benchmark/CMakeLists.txt
- extern/eigen3/CMakeLists.txt
- extern/fastor/CMakeLists.txt
- extern/googletest/CMakeLists.txt
- extern/vc/CMakeLists.txt
- extern/vecmem/CMakeLists.txt
The Vc library in particular is throwing a lot of warnings in the compilation of algebra-plugins and, in turn, in detray and traccc. This commit marks all of algebra-plugins' dependencies as system dependencies if allowed by CMake (i.e. on CMake 3.25 and later) to avoid the warnings.
> Include external libraries as system libraries

- tests/array/array_cmath.cpp
- tests/common/test_host_basics.hpp
- tests/eigen/eigen_cmath.cpp
- tests/eigen/eigen_eigen.cpp
- tests/fastor/fastor_fastor.cpp
- tests/smatrix/smatrix_cmath.cpp
- tests/smatrix/smatrix_smatrix.cpp
- tests/vecmem/vecmem_cmath.cpp
The current matrix testing code is a bit of a mess, with e.g. 2x2 matrix code hiding in the 3x3 matrix tests. This commit restructures the tests to make it clearer which tests live where. Also uses macros to make initializing the tests easier across a large range of front- and backends.
> Restructure matrix testing code

- cmake/algebra-plugins-functions.cmake
Made the benchmark build work correctly with MSVC. After #131 we collected the following type of warnings into our CI:
```
Creating library D:/a/algebra-plugins/algebra-plugins/build/lib/Debug/benchmark.lib and object D:/a/algebra-plugins/algebra-plugins/build/lib/Debug/benchmark.exp
benchmark.vcxproj -> D:\a\algebra-plugins\algebra-plugins\build\bin\Debug\benchmark.dll
Building Custom Rule D:/a/algebra-plugins/algebra-plugins/benchmarks/CMakeLists.txt
cl : command line  warning D9002: ignoring unknown option '-march=native' [D:\a\algebra-plugins\algebra-plugins\build\benchmarks\algebra_benchmark_array_getter.vcxproj]
cl : command line  warning D9002: ignoring unknown option '-ftree-vectorize' [D:\a\algebra-plugins\algebra-plugins\build\benchmarks\algebra_benchmark_array_getter.vcxproj] …
```
> MSVC Fix, main branch (2024.11.21.)

- .github/ci_setup.sh
- .github/workflows/builds.yml
- extern/vecmem/CMakeLists.txt
- math/common/include/algebra/math/common.hpp
- tests/accelerator/sycl/common/execute_sycl_test.hpp
- tests/accelerator/sycl/common/test_sycl_basics.hpp
Connected to #128, these updates are needed to be able to use [oneAPI 2025.0.0](https://www.intel.com/content/www/us/en/developer/articles/release-notes/intel-oneapi-toolkit-release-notes.html) with this project. With the hope that the latest version of oneAPI may work a little better. 🤔 (But also to be able to give our code to Intel developers, so that they could see the issues that we see, with the latest compilers.)
It will clash with #128, but we can just push that one in first, and then I'll resolve the one conflict I anticipate.
> SYCL2020 Updates, main branch (2024.11.19.)

- cmake/algebra-plugins-compiler-options-cpp.cmake
- common/include/algebra/concepts.hpp
- frontend/array_cmath/include/algebra/array_cmath.hpp
- frontend/eigen_eigen/CMakeLists.txt
- frontend/eigen_eigen/include/algebra/eigen_eigen.hpp
- frontend/eigen_generic/include/algebra/eigen_generic.hpp
- frontend/fastor_fastor/CMakeLists.txt
- frontend/fastor_fastor/include/algebra/fastor_fastor.hpp
- frontend/smatrix_generic/include/algebra/smatrix_generic.hpp
- frontend/smatrix_smatrix/CMakeLists.txt
- frontend/smatrix_smatrix/include/algebra/smatrix_smatrix.hpp
- frontend/vc_aos/CMakeLists.txt
- frontend/vc_aos/include/algebra/vc_aos.hpp
- frontend/vc_aos_generic/include/algebra/vc_aos_generic.hpp
- frontend/vc_soa/CMakeLists.txt
- frontend/vc_soa/include/algebra/vc_soa.hpp
- frontend/vecmem_cmath/include/algebra/vecmem_cmath.hpp
- math/generic/include/algebra/math/impl/generic_matrix.hpp
- tests/common/test_host_basics.hpp
Our current approach for e.g. matrix multiplication reads very naturally, e.g. `A = B*C` models $A = BC$, but this has a problem on GPU code. Indeed, if these matrices have size $N \times N$, then we first concretize an $N \times N$ matrix which we then have to copy element-by-element into $A$. This means that we need to keep that many registers live, which is quite large for e.g. $7 \times 7$ free matrices (which thus occupy 49 registers).
This problem can be alleviated by implementing optimized operators. More precisely, this PR implements the following new methods:
* `set_product(A, B, C)` computes $A = BC$ without intermediate values.
* `set_product_left_transpose(A, B, C)` computes $A = B^TC$ without intermediate values.
* `set_product_right_transpose(A, B, C)` computes $A = BC^T$ …
> Add new generic matrix operators

- frontend/array_cmath/include/algebra/array_cmath.hpp
- frontend/vecmem_cmath/include/algebra/vecmem_cmath.hpp
- math/eigen/include/algebra/math/impl/eigen_transform3.hpp
- storage/common/include/algebra/storage/matrix_getter.hpp
- storage/smatrix/include/algebra/storage/impl/smatrix_getter.hpp
- tests/common/test_device_basics.hpp
- tests/common/test_host_basics.hpp
The Eigen Identity matrix in the transform class leads to invalid instructions in CUDA. Also fixes small issues in the matrix getters of the Vc and SMatrix plugins.
Also moves the arithmetic operators of the cmath plugin to the algebra namespace, since they were picked up in ACTS builds by Eigen types
> fix: Eigen Identity matrix and Vc/SMatrix matrix getter and hide arithmetic operators in algebra namespace

- benchmarks/common/include/benchmark/common/benchmark_vector.hpp
- storage/vc_soa/include/algebra/storage/vc_soa.hpp
Try to fix google benchmark deprecation warning. Also uses explicit return types from the benchmark cases, to prevent spurious optimizations
> fix: benchmark deprecation warning

- benchmarks/array/array_matrix.cpp
- benchmarks/common/include/benchmark/common/benchmark_base.hpp
- benchmarks/common/include/benchmark/common/benchmark_matrix.hpp
- benchmarks/common/include/benchmark/common/benchmark_transform3.hpp
- benchmarks/common/include/benchmark/common/benchmark_vector.hpp
- benchmarks/common/include/benchmark/common/register_benchmark.hpp
- benchmarks/eigen/eigen_matrix.cpp
- benchmarks/vc_aos/vc_aos_matrix.cpp
- math/eigen/include/algebra/math/impl/eigen_matrix.hpp
Uses constexpr string views for the benchmarks names now and adds the new cases for the determinant and matrix inversion that were missing previously. The Eigen plugin inversion algorithm is returning a concrete type now in order to prevent expression templates to be handed through.
> feat: Cleanup benchmark names and add inversion and determinant

- frontend/array_cmath/include/algebra/array_cmath.hpp
- frontend/vc_aos/include/algebra/vc_aos.hpp
Fix the algorithm selector specification, which was lacking the element getter type, and add it to the Vc AoS plugin as well. This will now select the hard coded inversion and determinant algorithms for the 4x4 matrices correctly again.
> fix: algorithm selection for 4x4 matrices

- CMakeLists.txt
- README.md
- benchmarks/array/array_getter.cpp
- benchmarks/array/array_transform3.cpp
- benchmarks/array/array_vector.cpp
- benchmarks/eigen/eigen_getter.cpp
- benchmarks/eigen/eigen_matrix.cpp
- benchmarks/eigen/eigen_transform3.cpp
- benchmarks/eigen/eigen_vector.cpp
- benchmarks/vc_aos/vc_aos_getter.cpp
- benchmarks/vc_aos/vc_aos_matrix.cpp
- benchmarks/vc_aos/vc_aos_transform3.cpp
- benchmarks/vc_aos/vc_aos_vector.cpp
- benchmarks/vc_soa/vc_soa_getter.cpp
- benchmarks/vc_soa/vc_soa_transform3.cpp
- benchmarks/vc_soa/vc_soa_vector.cpp
- math/fastor/include/algebra/math/impl/fastor_vector.hpp
- math/vc_soa/include/algebra/math/impl/vc_soa_vector.hpp
I updated the README to reflect the `ALGEBRA_PLUGINS_BUILD_BENCHMARKS` CMake option.
A bunch of the benchmarking code source files either used `#include <string>` or had no `#include` whatsoever, but was using `std::cout`. I changed all of those to `#include <iostream>`.
Half of the Eigen benchmarks called the library "Eigen3" and the other half called it "Eigen". I changed it so that all of them just say "Eigen".
> Minor fixes and improvements

- benchmarks/CMakeLists.txt
- benchmarks/fastor/fastor_getter.cpp
- benchmarks/fastor/fastor_matrix.cpp
- benchmarks/fastor/fastor_transform3.cpp
- benchmarks/fastor/fastor_vector.cpp
- benchmarks/fastor/include/benchmark/fastor/data_generator.hpp
As the title states, I added Fastor to the benchmark suite so now, it emits all the `algebra_benchmark_fastor_{getter,transform3,matrix,vector}` binaries.
> Added Fastor to the benchmark suite

- utils/include/algebra/utils/print.hpp
Adds line breaks to the matrix output and aligns columns for better readability. Also sets the output of all vector and matrix elements to a fixed precision and scientific notation
> ref: Improve the stream operator for matrices and vectors

- common/include/algebra/type_traits.hpp
- math/fastor/include/algebra/math/impl/fastor_transform3.hpp
- storage/array/include/algebra/storage/array.hpp
- storage/common/include/algebra/storage/matrix.hpp
- storage/common/include/algebra/storage/vector.hpp
- storage/eigen/include/algebra/storage/eigen.hpp
- storage/fastor/include/algebra/storage/fastor.hpp
- storage/smatrix/include/algebra/storage/smatrix.hpp
- storage/vc_aos/CMakeLists.txt
- storage/vc_aos/include/algebra/storage/impl/vc_aos_approximately_equal.hpp
- storage/vc_aos/include/algebra/storage/vc_aos.hpp
- storage/vc_soa/include/algebra/storage/vc_soa.hpp
- storage/vecmem/include/algebra/storage/vecmem.hpp
- tests/common/test_host_basics.hpp
- tests/vc_soa/vc_soa.cpp
- utils/CMakeLists.txt
- utils/include/algebra/utils/approximately_equal.hpp
Implements an approximate equals function that works on algebra types. It is not foolproof for the comparison of any floating point numbers, so the google test version should be used in any actual tests.
Also adds a few missing typedefs to the algebras and fixes the `mat_scalar_t` type in the storage matrix and the comparison of the storage vector types, which came up during writing the tests for this PR
> feat: approximately equal for algebra types

- frontend/vc_soa/include/algebra/vc_soa.hpp
- math/eigen/CMakeLists.txt
- math/eigen/include/algebra/math/impl/eigen_transform3.hpp
- math/fastor/CMakeLists.txt
- math/fastor/include/algebra/math/impl/fastor_transform3.hpp
- math/generic/CMakeLists.txt
- math/generic/include/algebra/math/impl/generic_transform3.hpp
- math/smatrix/CMakeLists.txt
- math/smatrix/include/algebra/math/impl/smatrix_transform3.hpp
- math/vc_aos/CMakeLists.txt
- math/vc_aos/include/algebra/math/impl/vc_aos_transform3.hpp
- storage/vc_aos/CMakeLists.txt
- storage/vc_soa/CMakeLists.txt
- storage/vc_soa/include/algebra/storage/impl/vc_soa_casts.hpp
- storage/vc_soa/include/algebra/storage/vc_soa.hpp
- tests/common/test_host_basics.hpp
- tests/vc_soa/vc_soa.cpp
- utils/CMakeLists.txt
- utils/include/algebra/utils/casts.hpp
Implement functionality to cast algebra types to different floating point precision. This will be helpful in testing where floating point errors come from in downstream projects.
Edit: Also applied a sonar cloud suggestion on member initialization in the fastor transform type
> feat: Algebra type casts

- storage/cmath/include/algebra/storage/impl/cmath_getter.hpp
Add HIP runtime header for assert when compiling as a HIP source file: avoid host/device function issues.
> Fix debug compilation with HIP

- common/include/algebra/assert.hpp
- storage/cmath/include/algebra/storage/impl/cmath_getter.hpp
Move the HIP runtime  that is needed in one place for the assertion into a dedicated header to make it reusable
> ref: Move hip runtime for assertion into dedicated header
