acts-project/algebra-plugins

- CMakeLists.txt
- README.md
- common/CMakeLists.txt
- common/include/algebra/common/simd_types.hpp
- common/include/algebra/common/types.hpp
- core/include/array/CMakeLists.txt
- core/include/eigen/CMakeLists.txt
- core/include/smatrix/CMakeLists.txt
- core/include/vc/CMakeLists.txt
- extern/CMakeLists.txt
Includes vecmem for the algebra-plugins in preparation for a possible vecmem based plugin
> feat: Include vecmem for memory management

- core/common/include/algebra/common/definitions/array.hpp
- core/include/eigen/include/algebra/definitions/eigen.hpp
- core/include/smatrix/include/algebra/definitions/smatrix.hpp
- core/include/vc/include/algebra/definitions/vc_array.hpp
This PR adds inline qualifier to functions, to avoid duplicate definition errors and device code definition (w/ __host__ __device__ qualifier)
> add inline to functions

- core/include/array/CMakeLists.txt
- core/include/eigen/CMakeLists.txt
- core/include/smatrix/CMakeLists.txt
- core/include/vc/CMakeLists.txt
Some install paths are wrong currently...
> [bug] fix_install_path

- extern/CMakeLists.txt
update vecmem to v0.4.0
This will resolve acts-project/detray#102
> Update vecmem to v0.4.0

- frontend/array_cmath/include/algebra/array_cmath.hpp
- frontend/eigen_cmath/include/algebra/eigen_cmath.hpp
- frontend/smatrix_cmath/include/algebra/smatrix_cmath.hpp
- frontend/vc_cmath/include/algebra/vc_cmath.hpp
- frontend/vc_vc/include/algebra/vc_vc.hpp
- frontend/vecmem_cmath/include/algebra/vecmem_cmath.hpp
- math/cmath/include/algebra/math/algorithms/matrix/inverse/cofactor.hpp
- math/cmath/include/algebra/math/algorithms/matrix/inverse/hard_coded.hpp
Just trying to follow the original convention...
> change xxx_getter_type to xxx_getter

- README.md
Mirroring what we have in traccc.
> Add table to README.md

- frontend/vc_vc/include/algebra/vc_vc.hpp
- math/cmath/include/algebra/math/impl/cmath_matrix.hpp
- math/cmath/include/algebra/math/impl/cmath_operator.hpp
- math/cmath/include/algebra/math/impl/cmath_vector.hpp
- math/smatrix/include/algebra/math/impl/smatrix_matrix.hpp
- math/smatrix/include/algebra/math/impl/smatrix_vector.hpp
- math/vc/include/algebra/math/impl/vc_transform3.hpp
- storage/vc/include/algebra/storage/vc.hpp
- tests/common/test_host_basics.hpp
This PR adds some operations between matrix and vector and it is required by acts-project/detray#239
I had to mess up vc backend to make things work. But I think that's OK for now because vc backend should be rewritten from scratch anyway...
> Add operations between matrix and vector

- math/cmath/include/algebra/math/impl/cmath_matrix.hpp
> Remove commented lines

- frontend/vc_cmath/include/algebra/vc_cmath.hpp
> Use Vc array for vector method

- CMakeLists.txt
- extern/fastor/CMakeLists.txt
- extern/fastor/README.md
I've added Fastor as a math backend to the repository. This is step one to adding it as a full-fledged math backend, similar to Eigen and SMatrix.
> Added Fastor

- math/eigen/include/algebra/math/impl/eigen_getter.hpp
- math/eigen/include/algebra/math/impl/eigen_matrix.hpp
> Eigen getter size type template parameter

- frontend/eigen_cmath/include/algebra/eigen_cmath.hpp
- frontend/eigen_eigen/include/algebra/eigen_eigen.hpp
- math/cmath/include/algebra/math/algorithms/matrix/determinant/partial_pivot_lud.hpp
- math/cmath/include/algebra/math/algorithms/matrix/inverse/partial_pivot_lud.hpp
- math/cmath/include/algebra/math/impl/cmath_matrix.hpp
- math/cmath/include/algebra/math/impl/cmath_transform3.hpp
- math/eigen/include/algebra/math/impl/eigen_getter.hpp
- math/eigen/include/algebra/math/impl/eigen_matrix.hpp
- math/smatrix/include/algebra/math/impl/smatrix_getter.hpp
- tests/common/test_host_basics.hpp
Fixes a few implicit type conversions that caused compiler warnings in detray.
> fix: implicit conversions

- README.md
I updated the docs to include information about the Fastor plugin and also made a couple of other miscellaneous tweaks.
> Added some more info to the README.

- extern/eigen3/CMakeLists.txt
Hope it doesn't make any trouble...
> Update Eigen to 3.4.1

- math/cmath/include/algebra/math/impl/cmath_transform3.hpp
Vectorize the rotate function of cmath transform3
Also vectorized the `==` operator
> Vectorize the rotate function of cmath transform3

- math/cmath/include/algebra/math/impl/cmath_matrix.hpp
Explicitly initialize every element in array matrix
> fix: Zero init

- tests/common/test_host_basics.hpp
Add more tests on matrix inversion
> Add more tests on matrix inversion

- extern/benchmark/CMakeLists.txt
- extern/fastor/CMakeLists.txt
- extern/googletest/CMakeLists.txt
- extern/vc/CMakeLists.txt
- extern/vecmem/CMakeLists.txt
Update Fastor to version 0.6.4
Update google test to version 1.16.0
Update Vc to version 1.4.5
Update vecmem to version 1.14.0
> ref: Update externals

- cmake/algebra-plugins-compiler-options-cpp.cmake
- cmake/algebra-plugins-compiler-options-cuda.cmake
- cmake/algebra-plugins-compiler-options-sycl.cmake
See https://github.com/acts-project/detray/pull/956.
> Prevent CMake flags from propagating to parent

- CMakeLists.txt
This commit bumps the version number from v0.23.0 (oops!) to v0.28.0.
> Bump version number to v0.28.0
